Repository SMUMC-8th/SPRING_A, pull requests merged in 2025-05, with the labels that each got.

#2 ✨feat: 각 도메인에 대한 Entity 코드 작성
  src/main/java/com/project/teama_be/TeamABeApplication.java
  src/main/java/com/project/teama_be/domain/chat/entity/ChatMessage.java
  src/main/java/com/project/teama_be/domain/chat/entity/ChatParticipant.java
  src/main/java/com/project/teama_be/domain/chat/entity/ChatRoom.java
  src/main/java/com/project/teama_be/domain/location/entity/Location.java
  src/main/java/com/project/teama_be/domain/member/entity/Member.java
  src/main/java/com/project/teama_be/domain/member/entity/UserTerm.java
  src/main/java/com/project/teama_be/domain/member/enums/LoginType.java
  src/main/java/com/project/teama_be/domain/notification/entity/Notification.java
  src/main/java/com/project/teama_be/domain/notification/enums/NotificationStatus.java
  src/main/java/com/project/teama_be/domain/notification/enums/NotificationType.java
  src/main/java/com/project/teama_be/domain/post/entity/Comment.java
  src/main/java/com/project/teama_be/domain/post/entity/Post.java
  src/main/java/com/project/teama_be/domain/post/entity/PostImage.java
  src/main/java/com/project/teama_be/domain/post/entity/PostReaction.java
  src/main/java/com/project/teama_be/domain/post/entity/PostTag.java
  src/main/java/com/project/teama_be/domain/post/entity/Tag.java
  src/main/java/com/project/teama_be/global/entity/BaseEntity.java
Labels: ✨feature

#4 ✨feat: 응답정규화 및 Swagger 설정
  src/main/java/com/project/teama_be/global/apiPayload/CustomResponse.java
  src/main/java/com/project/teama_be/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/project/teama_be/global/apiPayload/code/GeneralErrorCode.java
  src/main/java/com/project/teama_be/global/apiPayload/exception/CustomException.java
  src/main/java/com/project/teama_be/global/apiPayload/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/project/teama_be/global/config/SwaggerConfig.java
  src/main/java/com/project/teama_be/global/utils/HttpResponseUtil.java
Labels: ✨feature

#6 ✨feat: Security 기본 설정 및 로그인 시 Cookie에 토큰 저장 로직 개발
  build.gradle
  src/main/java/com/project/teama_be/domain/location/entity/Location.java
  src/main/java/com/project/teama_be/domain/member/dto/request/MemberReqDTO.java
  src/main/java/com/project/teama_be/domain/member/entity/Member.java
  src/main/java/com/project/teama_be/domain/member/repository/MemberRepository.java
  src/main/java/com/project/teama_be/domain/post/entity/Comment.java
  src/main/java/com/project/teama_be/domain/post/entity/Post.java
  src/main/java/com/project/teama_be/global/config/CorsConfig.java
  src/main/java/com/project/teama_be/global/config/RedisConfig.java
  src/main/java/com/project/teama_be/global/security/annotation/CurrentUser.java
  src/main/java/com/project/teama_be/global/security/config/SecurityConfig.java
  src/main/java/com/project/teama_be/global/security/dto/JwtDTO.java
  src/main/java/com/project/teama_be/global/security/exception/JwtAccessDeniedHandler.java
  src/main/java/com/project/teama_be/global/security/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/project/teama_be/global/security/exception/SecurityErrorCode.java
  src/main/java/com/project/teama_be/global/security/filter/CustomLoginFilter.java
  src/main/java/com/project/teama_be/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/project/teama_be/global/security/userdetails/AuthUser.java
  src/main/java/com/project/teama_be/global/security/userdetails/CustomUserDetails.java
  src/main/java/com/project/teama_be/global/security/userdetails/CustomUserDetailsService.java
  src/main/java/com/project/teama_be/global/security/util/JwtUtil.java
  src/main/java/com/project/teama_be/global/utils/RedisUtil.java
Labels: ✨feature, ♻️refactor

#13 ✨feat: Member 도메인 Swagger 작성
  src/main/java/com/project/teama_be/domain/member/controller/AuthController.java
  src/main/java/com/project/teama_be/domain/member/controller/MemberController.java
  src/main/java/com/project/teama_be/domain/member/dto/request/MemberReqDTO.java
  src/main/java/com/project/teama_be/domain/member/dto/response/MemberResDTO.java
  src/main/java/com/project/teama_be/domain/member/service/JwtTokenService.java
  src/main/java/com/project/teama_be/global/security/filter/CustomLoginFilter.java
  src/main/java/com/project/teama_be/global/security/util/JwtUtil.java
Labels: ✨feature

#14 ✨ feat: 게시글 API 구현 (1/2)
  build.gradle
  src/main/java/com/project/teama_be/domain/location/repository/LocationRepository.java
  src/main/java/com/project/teama_be/domain/member/controller/AuthController.java
  src/main/java/com/project/teama_be/domain/post/controller/PostController.java
  src/main/java/com/project/teama_be/domain/post/converter/PostConverter.java
  src/main/java/com/project/teama_be/domain/post/converter/TagConverter.java
  src/main/java/com/project/teama_be/domain/post/dto/request/PostReqDTO.java
  src/main/java/com/project/teama_be/domain/post/dto/response/PostResDTO.java
  src/main/java/com/project/teama_be/domain/post/entity/Comment.java
  src/main/java/com/project/teama_be/domain/post/entity/Post.java
  src/main/java/com/project/teama_be/domain/post/entity/PostReaction.java
  src/main/java/com/project/teama_be/domain/post/entity/Tag.java
  src/main/java/com/project/teama_be/domain/post/exception/CommentException.java
  src/main/java/com/project/teama_be/domain/post/exception/PostException.java
  src/main/java/com/project/teama_be/domain/post/exception/code/CommentErrorCode.java
  src/main/java/com/project/teama_be/domain/post/exception/code/PostErrorCode.java
  src/main/java/com/project/teama_be/domain/post/repository/CommentRepository.java
  src/main/java/com/project/teama_be/domain/post/repository/PostImageRepository.java
  src/main/java/com/project/teama_be/domain/post/repository/PostQueryDsl.java
  src/main/java/com/project/teama_be/domain/post/repository/PostQueryDslImpl.java
  src/main/java/com/project/teama_be/domain/post/repository/PostReactionRepository.java
  src/main/java/com/project/teama_be/domain/post/repository/PostRepository.java
  src/main/java/com/project/teama_be/domain/post/repository/PostTagRepository.java
  src/main/java/com/project/teama_be/domain/post/repository/TagRepository.java
  src/main/java/com/project/teama_be/domain/post/service/command/PostCommandService.java
  src/main/java/com/project/teama_be/domain/post/service/query/PostQueryService.java
  src/main/java/com/project/teama_be/global/apiPayload/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/project/teama_be/global/aws/config/S3Config.java
  src/main/java/com/project/teama_be/global/aws/util/S3Util.java
  src/main/java/com/project/teama_be/global/config/QueryDslConfig.java
Labels: ✨feature, ♻️refactor

#23 🐛fix: 회원가입 시 발생하는 오류 해결
  src/main/java/com/project/teama_be/domain/member/controller/AuthController.java
  src/main/java/com/project/teama_be/global/config/WebConfig.java
  src/main/java/com/project/teama_be/global/converter/OctetStreamReadMsgConverter.java
Labels: 🐞bug, 🐛fix

#25 ♻️ refactor: S3Util, 파일 업로드 시 contentDisposition inline으로 설정
  src/main/java/com/project/teama_be/global/aws/util/S3Util.java
Labels: 🐞bug, 🐛fix

#41 🐛fix: FCM Token 저장 시 토큰 값만 저장되게 변경
  src/main/java/com/project/teama_be/domain/notification/controller/NotiController.java
  src/main/java/com/project/teama_be/domain/notification/converter/NotiConverter.java
  src/main/java/com/project/teama_be/domain/notification/dto/NotiResDTO.java
  src/main/java/com/project/teama_be/domain/notification/service/NotiService.java
  src/main/java/com/project/teama_be/global/utils/RedisUtil.java
Labels: 🐛fix, ♻️refactor

#45 ✨feat: Chat API 개발
  src/main/java/com/project/teama_be/domain/chat/controller/ChatController.java
  src/main/java/com/project/teama_be/domain/chat/converter/ChatRoomConverter.java
  src/main/java/com/project/teama_be/domain/chat/dto/request/ChatReqDTO.java
  src/main/java/com/project/teama_be/domain/chat/dto/response/ChatResDTO.java
  src/main/java/com/project/teama_be/domain/chat/entity/ChatParticipant.java
  src/main/java/com/project/teama_be/domain/chat/exception/ChatErrorCode.java
  src/main/java/com/project/teama_be/domain/chat/exception/ChatException.java
  src/main/java/com/project/teama_be/domain/chat/repository/ChatParticipantRepository.java
  src/main/java/com/project/teama_be/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/project/teama_be/domain/chat/service/command/ChatCommandService.java
  src/main/java/com/project/teama_be/domain/chat/service/command/SendBirdService.java
  src/main/java/com/project/teama_be/domain/chat/service/query/ChatQueryService.java
  src/main/java/com/project/teama_be/global/config/WebClientConfig.java
  src/main/java/com/project/teama_be/global/security/config/SecurityConfig.java
  src/main/java/com/project/teama_be/global/security/dto/AuthResDTO.java
  src/main/java/com/project/teama_be/global/security/filter/CustomLoginFilter.java
Labels: ✨feature, ♻️refactor
